#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libdbusmenu-qt
Version  : 0.9.3+16.04.20160218.0ubuntu1
Release  : 2
URL      : https://github.com/unity8-team/libdbusmenu-qt/archive/0.9.3+16.04.20160218-0ubuntu1.tar.gz
Source0  : https://github.com/unity8-team/libdbusmenu-qt/archive/0.9.3+16.04.20160218-0ubuntu1.tar.gz
Summary  : Qt implementation of dbusmenu spec
Group    : Development/Tools
License  : LGPL-2.0
Requires: libdbusmenu-qt-lib = %{version}-%{release}
Requires: libdbusmenu-qt-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : doxygen

%description
# Summary
This library provides a Qt implementation of the DBusMenu protocol.
The DBusMenu protocol makes it possible for applications to export and import
their menus over DBus.

%package dev
Summary: dev components for the libdbusmenu-qt package.
Group: Development
Requires: libdbusmenu-qt-lib = %{version}-%{release}
Provides: libdbusmenu-qt-devel = %{version}-%{release}

%description dev
dev components for the libdbusmenu-qt package.


%package doc
Summary: doc components for the libdbusmenu-qt package.
Group: Documentation

%description doc
doc components for the libdbusmenu-qt package.


%package lib
Summary: lib components for the libdbusmenu-qt package.
Group: Libraries
Requires: libdbusmenu-qt-license = %{version}-%{release}

%description lib
lib components for the libdbusmenu-qt package.


%package license
Summary: license components for the libdbusmenu-qt package.
Group: Default

%description license
license components for the libdbusmenu-qt package.


%prep
%setup -q -n libdbusmenu-qt-0.9.3-16.04.20160218-0ubuntu1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549463343
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1549463343
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libdbusmenu-qt
cp COPYING %{buildroot}/usr/share/package-licenses/libdbusmenu-qt/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/dbusmenu-qt5/dbusmenu_export.h
/usr/include/dbusmenu-qt5/dbusmenu_version.h
/usr/include/dbusmenu-qt5/dbusmenuexporter.h
/usr/include/dbusmenu-qt5/dbusmenuimporter.h
/usr/lib64/cmake/dbusmenu-qt5/dbusmenu-qt5-config-version.cmake
/usr/lib64/cmake/dbusmenu-qt5/dbusmenu-qt5-config.cmake
/usr/lib64/cmake/dbusmenu-qt5/dbusmenu-qt5-targets-relwithdebinfo.cmake
/usr/lib64/cmake/dbusmenu-qt5/dbusmenu-qt5-targets.cmake
/usr/lib64/libdbusmenu-qt5.so
/usr/lib64/pkgconfig/dbusmenu-qt5.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libdbusmenu-qt5-doc/annotated.html
/usr/share/doc/libdbusmenu-qt5-doc/bc_s.png
/usr/share/doc/libdbusmenu-qt5-doc/bdwn.png
/usr/share/doc/libdbusmenu-qt5-doc/classDBusMenuExporter-members.html
/usr/share/doc/libdbusmenu-qt5-doc/classDBusMenuExporter.html
/usr/share/doc/libdbusmenu-qt5-doc/classDBusMenuExporter.png
/usr/share/doc/libdbusmenu-qt5-doc/classDBusMenuImporter-members.html
/usr/share/doc/libdbusmenu-qt5-doc/classDBusMenuImporter.html
/usr/share/doc/libdbusmenu-qt5-doc/classDBusMenuImporter.png
/usr/share/doc/libdbusmenu-qt5-doc/classes.html
/usr/share/doc/libdbusmenu-qt5-doc/closed.png
/usr/share/doc/libdbusmenu-qt5-doc/dbusmenu__export_8h_source.html
/usr/share/doc/libdbusmenu-qt5-doc/dbusmenuexporter_8h_source.html
/usr/share/doc/libdbusmenu-qt5-doc/dbusmenuimporter_8h_source.html
/usr/share/doc/libdbusmenu-qt5-doc/deprecated.html
/usr/share/doc/libdbusmenu-qt5-doc/dir_68267d1309a1af8e8297ef4c3efbcdba.html
/usr/share/doc/libdbusmenu-qt5-doc/doc.png
/usr/share/doc/libdbusmenu-qt5-doc/doxygen.css
/usr/share/doc/libdbusmenu-qt5-doc/doxygen.png
/usr/share/doc/libdbusmenu-qt5-doc/dynsections.js
/usr/share/doc/libdbusmenu-qt5-doc/files.html
/usr/share/doc/libdbusmenu-qt5-doc/folderclosed.png
/usr/share/doc/libdbusmenu-qt5-doc/folderopen.png
/usr/share/doc/libdbusmenu-qt5-doc/functions.html
/usr/share/doc/libdbusmenu-qt5-doc/functions_func.html
/usr/share/doc/libdbusmenu-qt5-doc/hierarchy.html
/usr/share/doc/libdbusmenu-qt5-doc/index.html
/usr/share/doc/libdbusmenu-qt5-doc/jquery.js
/usr/share/doc/libdbusmenu-qt5-doc/menu.js
/usr/share/doc/libdbusmenu-qt5-doc/menudata.js
/usr/share/doc/libdbusmenu-qt5-doc/nav_f.png
/usr/share/doc/libdbusmenu-qt5-doc/nav_g.png
/usr/share/doc/libdbusmenu-qt5-doc/nav_h.png
/usr/share/doc/libdbusmenu-qt5-doc/open.png
/usr/share/doc/libdbusmenu-qt5-doc/pages.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_0.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_0.js
/usr/share/doc/libdbusmenu-qt5-doc/search/all_1.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_1.js
/usr/share/doc/libdbusmenu-qt5-doc/search/all_2.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_2.js
/usr/share/doc/libdbusmenu-qt5-doc/search/all_3.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_3.js
/usr/share/doc/libdbusmenu-qt5-doc/search/all_4.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_4.js
/usr/share/doc/libdbusmenu-qt5-doc/search/all_5.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_5.js
/usr/share/doc/libdbusmenu-qt5-doc/search/all_6.html
/usr/share/doc/libdbusmenu-qt5-doc/search/all_6.js
/usr/share/doc/libdbusmenu-qt5-doc/search/classes_0.html
/usr/share/doc/libdbusmenu-qt5-doc/search/classes_0.js
/usr/share/doc/libdbusmenu-qt5-doc/search/close.png
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_0.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_0.js
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_1.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_1.js
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_2.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_2.js
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_3.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_3.js
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_4.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_4.js
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_5.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_5.js
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_6.html
/usr/share/doc/libdbusmenu-qt5-doc/search/functions_6.js
/usr/share/doc/libdbusmenu-qt5-doc/search/mag_sel.png
/usr/share/doc/libdbusmenu-qt5-doc/search/nomatches.html
/usr/share/doc/libdbusmenu-qt5-doc/search/pages_0.html
/usr/share/doc/libdbusmenu-qt5-doc/search/pages_0.js
/usr/share/doc/libdbusmenu-qt5-doc/search/search.css
/usr/share/doc/libdbusmenu-qt5-doc/search/search.js
/usr/share/doc/libdbusmenu-qt5-doc/search/search_l.png
/usr/share/doc/libdbusmenu-qt5-doc/search/search_m.png
/usr/share/doc/libdbusmenu-qt5-doc/search/search_r.png
/usr/share/doc/libdbusmenu-qt5-doc/search/searchdata.js
/usr/share/doc/libdbusmenu-qt5-doc/splitbar.png
/usr/share/doc/libdbusmenu-qt5-doc/sync_off.png
/usr/share/doc/libdbusmenu-qt5-doc/sync_on.png
/usr/share/doc/libdbusmenu-qt5-doc/tab_a.png
/usr/share/doc/libdbusmenu-qt5-doc/tab_b.png
/usr/share/doc/libdbusmenu-qt5-doc/tab_h.png
/usr/share/doc/libdbusmenu-qt5-doc/tab_s.png
/usr/share/doc/libdbusmenu-qt5-doc/tabs.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdbusmenu-qt5.so.2
/usr/lib64/libdbusmenu-qt5.so.2.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libdbusmenu-qt/COPYING
